baseUrl: "https://azulwasi.docs.providencehealthtech.com"
copyright: "Copyright &copy; 2021-2022<br>Providence HealthTech.<br>All Rights Reserved."
defaultContentLanguage: "en"
defaultContentLanguageInSubdir: true
disableHugoGeneratorInject: true
enableEmoji: true
paginate: 25
timeZone: "America/New_York"
title: "Azul Wasi OpenEMR Pocket Guide"
theme: "hugo-geekdoc"
params:
  # geekdocDarkModeDim: true
  # geekdocMenuBundle: true
